services:
  web:
    container_name: weather-tests-local
    build:
      dockerfile: local.Dockerfile
    ports:
      - "8081:8081"
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: local